artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion

  # Classification data configuration
  classification:
    source_path: project_data/preprocessed_churn_data.csv
    local_data_file: artifacts/data_ingestion/classification_data.csv

  # Regression data configuration
  regression:
    source_path: project_data/preprocessed_forecast_data.csv
    local_data_file: artifacts/data_ingestion/regression_data.csv
